// English, Norwegian, German, Italian, French, Spanish.
// Shared rows keep these dialog labels and messages available in every UI locale.
static const wchar_t* const kDialogTranslations[][6] = {
    {L"Variant", L"Variant", L"Variante", L"Variante", L"Variante", L"Variante"},
    {L"Move left", L"Flytt til venstre", L"Nach links", L"Sposta a sinistra", L"Déplacer à gauche", L"Mover a la izquierda"},
    {L"Move right", L"Flytt til høyre", L"Nach rechts", L"Sposta a destra", L"Déplacer à droite", L"Mover a la derecha"},
    {L"Combination details - SwashMoji", L"Kombinasjonsdetaljer – SwashMoji", L"Kombinationsdetails – SwashMoji", L"Dettagli combinazione – SwashMoji", L"Détails de la combinaison – SwashMoji", L"Detalles de combinación – SwashMoji"},
    {L"Exact sequence", L"Nøyaktig sekvens", L"Exakte Reihenfolge", L"Sequenza esatta", L"Séquence exacte", L"Secuencia exacta"},
    {L"Emoji in insertion order", L"Emojier i innsettingsrekkefølge", L"Emojis in Einfügereihenfolge", L"Emoji in ordine di inserimento", L"Émojis dans l’ordre d’insertion", L"Emojis en orden de inserción"},
    {L"Delete combination", L"Slett kombinasjon", L"Kombination löschen", L"Elimina combinazione", L"Supprimer la combinaison", L"Eliminar combinación"},
    {L"Affected aliases", L"Berørte aliaser", L"Betroffene Aliase", L"Alias interessati", L"Alias concernés", L"Alias afectados"},
    {L"Delete this combination, its favorites, learned history, and the aliases listed below?", L"Slette denne kombinasjonen, favorittene, den lærte historikken og aliasene nedenfor?", L"Diese Kombination, ihre Favoriten, den gelernten Verlauf und die unten aufgeführten Aliase löschen?", L"Eliminare questa combinazione, i suoi preferiti, la cronologia appresa e gli alias elencati sotto?", L"Supprimer cette combinaison, ses favoris, son historique appris et les alias ci-dessous ?", L"¿Eliminar esta combinación, sus favoritos, el historial aprendido y los alias indicados abajo?"},
    {L"Favorites saved.", L"Favoritter lagret.", L"Favoriten gespeichert.", L"Preferiti salvati.", L"Favoris enregistrés.", L"Favoritos guardados."},
    {L"Alias saved.", L"Alias lagret.", L"Alias gespeichert.", L"Alias salvato.", L"Alias enregistré.", L"Alias guardado."},
    {L"Alias deleted.", L"Alias slettet.", L"Alias gelöscht.", L"Alias eliminato.", L"Alias supprimé.", L"Alias eliminado."},
    {L"Combination saved.", L"Kombinasjon lagret.", L"Kombination gespeichert.", L"Combinazione salvata.", L"Combinaison enregistrée.", L"Combinación guardada."},
    {L"Combination deleted.", L"Kombinasjon slettet.", L"Kombination gelöscht.", L"Combinazione eliminata.", L"Combinaison supprimée.", L"Combinación eliminada."},
    {L"No dependent aliases.", L"Ingen avhengige aliaser.", L"Keine abhängigen Aliase.", L"Nessun alias dipendente.", L"Aucun alias dépendant.", L"No hay alias dependientes."},
    {L"New combination / edit...", L"Ny kombinasjon / rediger …", L"Neue Kombination / bearbeiten …", L"Nuova combinazione / modifica…", L"Nouvelle combinaison / modifier…", L"Nueva combinación / editar…"},
    {L"Details - SwashMoji", L"Detaljer – SwashMoji", L"Details – SwashMoji", L"Dettagli – SwashMoji", L"Détails – SwashMoji", L"Detalles – SwashMoji"},
    {L"Variant for the next insertion or copy", L"Variant for neste innsetting eller kopiering", L"Variante für das nächste Einfügen oder Kopieren", L"Variante per il prossimo inserimento o copia", L"Variante pour la prochaine insertion ou copie", L"Variante para la próxima inserción o copia"},
    {L"Use once keeps your global skin tone unchanged.", L"Bruk én gang beholder den globale hudtonen.", L"Einmal verwenden lässt den globalen Hautton unverändert.", L"Usa una volta mantiene la tonalità della pelle globale.", L"Utiliser une fois conserve la couleur de peau globale.", L"Usar una vez conserva el tono de piel global."},
    {L"Use once", L"Bruk én gang", L"Einmal verwenden", L"Usa una volta", L"Utiliser une fois", L"Usar una vez"},
    {L"Start SwashMoji when I sign in to Windows", L"Start SwashMoji når jeg logger på Windows", L"SwashMoji bei der Windows-Anmeldung starten", L"Avvia SwashMoji all’accesso a Windows", L"Lancer SwashMoji à l’ouverture de session Windows", L"Iniciar SwashMoji al iniciar sesión en Windows"},
    {L"Uses this copy of SwashMoji. Save again after moving it. Windows Startup apps must also allow it.", L"Bruker denne kopien av SwashMoji. Lagre på nytt hvis du flytter den. Windows må også tillate oppstart.", L"Verwendet diese Kopie von SwashMoji. Nach dem Verschieben erneut speichern. Windows muss den Autostart ebenfalls erlauben.", L"Usa questa copia di SwashMoji. Salva di nuovo dopo averla spostata. Anche Windows deve consentire l’avvio automatico.", L"Utilise cette copie de SwashMoji. Enregistrez à nouveau après l’avoir déplacée. Windows doit aussi autoriser son démarrage.", L"Usa esta copia de SwashMoji. Guarda de nuevo si la mueves. Windows también debe permitir su inicio automático."},
    {L"Open picker shortcut:", L"Snarvei for å åpne velgeren:", L"Tastenkürzel zum Öffnen:", L"Scorciatoia di apertura:", L"Raccourci d’ouverture :", L"Atajo para abrir el selector:"},
    {L"Key:", L"Tast:", L"Taste:", L"Tasto:", L"Touche :", L"Tecla:"},
    {L"Reset to Alt+E", L"Tilbakestill til Alt+E", L"Auf Alt+E zurücksetzen", L"Ripristina Alt+E", L"Rétablir Alt+E", L"Restablecer Alt+E"},
};
